### ISSUE TITLE
Error "NetCDF: Numeric conversion not representable:" in the default run

### ISSUE THREAD

**Issue by fgr81** [nasa/AmesGCM#2]
Hi,

  I've compiled the model and now I'm trying to run the model along the default configuration. 

When the simulation reaches the fifth sol, it crashes releasing this log:

```
 Sol =           5    sec =         924
 ZS      14850.797524433967       -7155.5411509483538       -552.60350009166507
 PS max =    12.717273749093815       min =    1.6980389067447610
 Total surface pressure (Pa) =    703.19290059204172
 UA_top max =    243.91505844643021       min =   -325.85808677782836
 UA max =    243.91505844643021       min =   -325.85808677782836
 VA max =    264.95307557108612       min =   -281.93776836950821
 TA max =    258.02339505571615       min =    104.25630491812247
 OM max =    3.2089082533056326E-002  min =   -4.1935912669667647E-002
 dummy_tracer max =    0.0000000000000000       min =    0.0000000000000000
 h2o_vapor max =    2.4277096540360093E-007  min =    3.4166455680323792E-056
 tracer1 max =    0.0000000000000000       min =    0.0000000000000000
 dst_mass_mom max =                        NaN  min =                        NaN
 dst_num_mom max =                        NaN  min =                        NaN
 ice_mass_mom max =    0.0000000000000000       min =    0.0000000000000000
 ice_num_mom max =    0.0000000000000000       min =    0.0000000000000000
 cor_mass_mom max =    0.0000000000000000       min =    0.0000000000000000
 vap_mass_mom max =    2.4283523598000939E-007  min =    3.4167158134224206E-056
 ice_cloud max =    0.0000000000000000       min =    0.0000000000000000

```

and with this error:

```
FATAL from PE    18: NetCDF: Numeric conversion not representable: netcdf_write_data_4d: file:atmos_average.tile4.nc variable: dst_mass_source


FATAL from PE    12: NetCDF: Numeric conversion not representable: netcdf_write_data_4d: file:atmos_average.tile3.nc variable: dst_mass_source


FATAL from PE     0: NetCDF: Numeric conversion not representable: netcdf_write_data_4d: file:atmos_average.tile1.nc variable: dst_mass_source


FATAL from PE     0: NetCDF: Numeric conversion not representable: netcdf_write_data_4d: file:atmos_average.tile1.nc variable: dst_mass_source


FATAL from PE    24: NetCDF: Numeric conversion not representable: netcdf_write_data_4d: file:atmos_average.tile5.nc variable: dst_mass_source

```
In the directory I've the following files in which the variables are empty:
atmos_diurn.tile[1..6].nc
atmos_davg.tile[1..6].nc
atmos_daily.tile[1..6].nc
atmos_average.tile[1..6].nc

Is there an error in the simulation config ?

**Comment by rurata** [comment]
Hi Fabio,
The log shows that dst_mass_mom and dst_num_mom are NaNs. The model is crashing because the NaNs cannot be written out to the history file. It is difficult to diagnose the cause of the NaNs, but it could be that the dust file is not being copied to the INPUT directory properly. Could you check the INPUT directory for a dust_cycle.nc file?

**Comment by fgr81** [comment]
Hi Richards, thank you very much for your attention. 

I'm using the script AM4/exec/fms_mars_default_v3.1 which points to AM4/src/AmesGCM/data/DustScenario_Background.nc  that doesn't contain the variables _dst_mass_mom_ and _dst_num_mom_ . 

I dumped the others DustScenarioXYZ.nc in the same folder and none has those variables but only:

```
ncdump -h DustScenario_MY24.nc 
netcdf DustScenario_MY24 {
dimensions:
	time = 668 ;
	lat = 60 ;
	lon = 120 ;
	latb = 61 ;
	lonb = 121 ;
variables:
	float time(time) ;
		time:units = "days" ;
		time:long_name = "time" ;
	float lat(lat) ;
		lat:units = "degrees_north " ;
		lat:long_name = "latitude" ;
	float lon(lon) ;
		lon:units = "degrees_east   " ;
		lon:long_name = "longitude" ;
	float latb(latb) ;
		latb:units = "degrees" ;
		latb:long_name = "arbitrary long_name" ;
	float lonb(lonb) ;
		lonb:units = "degrees" ;
		lonb:long_name = "arbitrary long_name" ;
	float areo(time) ;
		areo:units = "areocentric longitude" ;
	float zmax(time, lat, lon) ;
		zmax:units = "height  (km)" ;
	float tau(time, lat, lon) ;
		tau:units = "opacity  (dimensionless)" ;
	float taufill(time, lat, lon) ;
		taufill:units = "opacity  (dimensionless)" ;
}

```

Where could I find  the exact DustScenario(s) ?

**Comment by rurata** [comment]
The dust scenario files contain dust opacity maps for a particular Mars Year, except the background file which is a composite of the minimum opacities for each latitude over a number of Mars Years. The model lifts mass and number in order to match the opacity in the dust maps on any given day. The dust scenario file in the data directory should be copied to your run_dir/INPUT directory as dust_cycle.nc.

**Comment by fgr81** [comment]
Where could I download these scenarios nor how could I prepare them ?

**Comment by rurata** [comment]
Some scenarios are included in the data directory. Other scenarios for MY24-MY34 can be made available upon request. You can prepare your own dust scenarios by creating files with the same variables, and filling zmax (km), tau (visible OD), taufill (visible OD) with appropriate values.

**Comment by fgr81** [comment]
Thank you Richard, I found out that it's a numerical stability problem that I solved.
