### ISSUE TITLE
Dust Mixing Ratio

### ISSUE THREAD

**Issue by fgr81** [nasa/AmesGCM#3]
Hi,

  I'd like to reproduce the  [2.9 Exercise](https://github.com/NASA-Planetary-Science/AmesCAP/blob/0a61614f41a21246a4343711fdabc5cabf80e8ef/tutorial/CAP_Exercises_2021.md) but in my daily data there isn't dst_mass variable; can I add it in my diag_table ?  In the User Guide  I read this:

```
The field table is located in-line in the runscript and is used to define additional fields known as
“tracers” in the simulation. MGCM 3.1 carries multiple (dust and water) tracers that are discon-
nected from any physics routines, are always zero, and are thus not supported in this release. These
tracers are required for the radiation code and will be connected (with appropriate physics) and
supported in a future public release of the model. Although MGCM 3.1 does not carry supported
tracers, we provide a brief description of the field table here because it appears in the runscript.
```

I fear that I have been denied this possibility.

Thanx for your time, best regards

-fabio grasso-

**Comment by rurata** [comment]
Hi Fabio,
You should be able to add dst_mass to your diag_table with this line:
"dynamics",     "dst_mass_mom", "dst_mass", "atmos_daily", "all", .false.,      "none", 2,

It appears that these lines in the User Guide are outdated. Version 3.1 should have dust tracers connected to the dust cycle.

**Comment by fgr81** [comment]
Hi Richard, thank you so much, it seems to be OK !

Regards, 

-fabio-
